/*export PRJ_PATH=$(shell pwd)/..
export DESIGN=top

cmp:
	verilator -Wno-fatal top.v 1.cpp --top-module $(DESIGN) --cc --trace --exe
	#make -C obj_dir -f V$(DESIGE).mk V$(DESING)

run:
	./obj_dir/v$(DESIGE)

wave:
	gtkwave wave.vcd &

clean:
	@rm -rf obj_dir wave.vcd*/
